name: "Publish (auto)"

env:
  GIT_AUTHOR_NAME: "SWC Bot"
  GIT_AUTHOR_EMAIL: "bot@swc.rs"
  GIT_COMMITTER_NAME: "SWC Bot"
  GIT_COMMITTER_EMAIL: "bot@swc.rs"

on:
  workflow_dispatch:
  pull_request:
    types: ["opened", "reopened", "synchronize"]

jobs:
  publish-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "swc-project/swc"
          ref: "main"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "xtask-only"
          cache-on-failure: true

      - name: Install cargo-mono
        uses: baptiste0928/cargo-install@v2.2.0
        with:
          crate: cargo-edit
          version: "0.12.2"
          locked: true
  
      - run: cargo xtask npm nightly --git

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SWC_BOT_SSH }}

        # Push back, using ssh
      - name: Push back
        run: |
          git push git@github.com:swc-project/swc.git --no-verify
          git push git@github.com:swc-project/swc.git --no-verify --tags
